RUN (apt-get update || true) && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confold" autoconf build-essential pie-zts && \
    pie-zts install asgrim/example-pie-extension
